GRANT USAGE ON SCHEMA pmb TO "apps";
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA pmb TO "apps";
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA pmb TO "apps";
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA pmb TO "apps";